# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# Had to remove because of jekyll 3 compatibility
# relative_permalinks: true

# Setup
title:               Tópicos Especiais em Algoritmos
tagline:             'Ciência da Computação'
description:         'Material auxiliar da disciplina Tópicos Especiais em Algoritmos do curso superior de Ciência da Computação do IFB-Taguatinga.'

url:                 https://danielsaad.com/TEA-BCC-IFB
# url: http://localhost

paginate:            5
mathjax: true
syntax_highlighter: pygments
# About/contact
author:
  name:              Daniel Saad Nogueira Nunes
  url:               https://danielsaad.com
  email:             daniel.nunes@ifb.ebu.br

# Custom vars
version:             1.0.0
plugins: [jekyll-paginate]

markdown: kramdown

kramdown:
  parse_block_html: true